# Example build command
# From repository root folder
# docker build --build-arg ENV=development -t police-data-trust-frontend-dev -f frontend/Dockerfile.cloud ./frontend

FROM node:14.18.0-buster as builder

WORKDIR /app/
ARG ENV

COPY package*.json ./
RUN npm ci --no-optional --quiet 1>/dev/null
RUN npm install --global env-cmd

COPY . .

RUN npm run build:${ENV}

FROM nginx:1.21.3
COPY --from=builder /app/out /usr/share/nginx/html
EXPOSE 80
