import type { Metadata } from "next";
import "./globals.css";
import Nav from "@/components/Nav/nav";
import { inter, roboto } from "@/app/font";
import MobileNav from "../components/mobile_nav/mobileNav";
import { AuthProvider } from "@/context/AuthProvider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <AuthProvider>
        <body className= {`${inter.variable} ${roboto}`}>
          <Nav />
          <main>
            {children}
          </main>
          <MobileNav />
        </body>
      </AuthProvider>
    </html>
  );
}