import type { Metadata } from "next";
import "./globals.css";
import Nav from "@/app/component/nav";
import { inter, roboto } from "@/app/font";
import MobileNav from "./component/mobileNav";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className= {`${inter.variable} ${roboto}`}>
        <Nav />
        <main>
          {children}
        </main>
        <MobileNav />
      </body>
    </html>
  );
}
