resources:
  varname_crosswalk: 'backend/scraper/varnames_crosswalk.csv'

sources:
  mpv:
      url: https://mappingpoliceviolence.org/s/MPVDatasetDownload.xlsx
      type: news article
      id: mpv_id
  cpdp:
      url: https://github.com/invinst/chicago-police-data/raw/master/data/unified_data.zip
      type: government record
      id: cr_id
      headdirectory: fully-unified-data
      subdirectory: complaints
      location: .
  fatal:
      url: https://raw.githubusercontent.com/washingtonpost/data-police-shootings/master/fatal-police-shootings-data.csv
      type: news article
      id: id
      location: .
  counted:
      url: https://interactive.guim.co.uk/2015/the-counted/thecounted-data.zip
      type: news article
      id: uid
      headdirectory: thecounted-data
      subdirectory: None
      location: thecounted-data
tables:
  report:
    required:
      - record_id
      - data_source_id
      - record_type
      - attachments_available
    optional:
      - null
  incident:
    required:
      - record_id
      - incident_date
      - incident_time
      - death_location_street_address
      - death_location_city
      - death_location_county
      - death_location_state
      - description
      - perpetrator
      - department_present
    optional:
      - incident_type
  victim:
    required:
      - null
    optional:
      - victim_name_full
      - victim_sex
      - victim_age
      - victim_race
  death:
    required:
      - null
    optional:
      - death_manner