openapi: "3.0.3"
info:
  title: "Incidents"
  description: "API Description"
  version: "0.1.0"
servers:
  - url: "http://dev-api.nationalpolicedfata.org/api/v1"
    description: "Development environment"
  - url: "https://stage-api.nationalpolicedata.org/api/v1"
    description: "Staging environment"
  - url: "https://api.nationalpolicedata.org"
    description: "Production environment"
x-readme:
  explorer-enabled: true
  proxy-enabled: true
  samples-enabled: true
security:
  - bearerAuth: []
tags:
  - name: "Incidents"
    description: "Incident related endpoints"
paths:
  /incidents/{incident_id}:
    parameters:
      - name: incident_id
        in: path
        required: true
        schema:
          type: string
    get:
      summary: "Get Incident"
      operationId: "getIncident"
      description: >
        Returns information about a single incident.
      responses:
        "200":
          description: "An incident object"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Incident"
        '404':
          $ref: '../common/error.yaml#/components/responses/notFoundError'
    patch: 
      summary: "Update Incident"
      operationId: "updateIncident"
      description: >
        Update a single incident. Only an admin of the contributing
        organization or the original user who submitted the incident
        can update the incident.
      requestBody:
        description: "Incident object that needs to be updated in the database"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateIncident"
      responses:
        "200":
          description: "An incident object"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Incident"
        '400':
          $ref: '../common/error.yaml#/components/responses/validationError'
        '404':
          $ref: '../common/error.yaml#/components/responses/notFoundError'
      
  /incidents:
    post:
      summary: "Create Incident"
      operationId: "createIncident"
      description: >
        Create a single incident. User must be a
        contributor to create an incident.
      requestBody:
        description: "Incident object that needs to be added to the database"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateIncident"
      responses:
        "200":
          description: "A JSON array of user names"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Incident"
        '400':
          $ref: '../common/error.yaml#/components/responses/validationError'
    get:
      summary: "Get all Incidents"
      operationId: "getIncidents"
      description: >
       Returns all incidents in the database. Filters can be applied
       to narrow down the results.
      parameters:
        - $ref: '../common/pagination.yaml#/components/parameters/page'
        - $ref: '../common/pagination.yaml#/components/parameters/per_page'
      responses:
        "200":
          description: "A JSON array of incident objects"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/IncidentList"
  /incidents/matchPerpetrator:
    post:
      summary: "Match Perpetrator"
      operationId: "matchPerpetrator"
      description: >
        Identifies potential matches for a perpetrator based on the
        provided information. 
      requestBody:
        content: 
          application/json:
            schema:
              $ref: "#/components/schemas/Perpetrator"
      responses:
        "200":
          description: "A set of possible matches for the perpetrator."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PerpetratorMatches"
        '400':
          $ref: '../common/error.yaml#/components/responses/validationError'
components:
  schemas:
    BaseIncident:
      type: "object"
      description: "Base incident object"
      properties:
        source_id:
          type: "string"
          description: "The ID of the partner that reported the incident."
        date_record_created:
          type: "string"
          format: "date-time"
          description: "The date and time the incident was recorded."
        time_of_incident:
          type: "string"
          format: "date-time"
          description: "The date and time the incident occurred."
        time_confidence:
          type: "string"
          description: "The confidence level of the time of the incident."
        complaint_date:
          type: "string"
          format: "date-time"
          description: "The date the complaint was filed."
        closed_date:
          type: "string"
          format: "date-time"
          description: "The date the incident was closed."
        location:
          type: "string"
          description: "The location of the incident."
        latitude:
          type: "number"
          description: "The latitude of the incident."
        longitude:
          type: "number"
          description: "The longitude of the incident."
        description:
          type: "string"
          description: "A description of the incident."
        stop_type:
          type: "string"
          description: "The type of stop."
        call_type:
          type: "string"
          description: "The type of call."
        has_attachments:
          type: "boolean"
          description: "Whether the incident has attachments."
        from_report:
          type: "boolean"
          description: "Whether the incident was reported."
        was_victim_arrested:
          type: "boolean"
          description: "Whether the victim was arrested."
        was_victim_charged:
          type: "boolean"
          description: "Whether a criminal case was brought."
        was_citation_issued:
          type: "boolean"
          description: "Whether a citation was issued."
        criminal_case_id:
          type: "string"
          description: "The ID of the criminal case."
        complaintant:
          type: "array"
          description: "The aggrevated party. The name of the person who filed the complaint might not be included with the record if the complaint was reported through counsel."
          items:
            $ref: "#/components/schemas/Victim"
        perpetrators:
          type: "array"
          description: "Officers involved in the incident"
          items:
            $ref: "#/components/schemas/Perpetrator"
        participants:
          type: "array"
          description: "Named individuals who are neither complaintants nor perpetrators."
          items:
            $ref: "#/components/schemas/Participant"
        attachements:
          type: "array"
          description: "Multimedia associated with the incident"
          items:
            $ref: "#/components/schemas/Multimedia"
        investigations:
          type: "array"
          description: "Investigations associated with the incident"
          items:
            $ref: "#/components/schemas/Investigation"
        results_of_stop:
          type: "array"
          description: "Results of stop associated with the incident"
          items:
            $ref: "#/components/schemas/ResultOfStop"
        actions:
          type: "array"
          description: "Actions associated with the incident"
          items:
            $ref: "#/components/schemas/Action"
        use_of_force:
          type: "array"
          description: "Use of force associated with the incident"
          items:
            $ref: "#/components/schemas/UseOfForce"
        
    CreateIncident:
      type: "object"
      description: "Incident object"
      properties:
        victims:
          type: "array"
          description: "Victims of the incident"
          items:
            $ref: "#/components/schemas/Victim"
        officers:
          type: "array"
          description: "Officers involved in the incident"
          items:
            $ref: "#/components/schemas/Officer"
        tags:
          type: "array"
          description: "Tags associated with the incident"
          items:
            type: "string"
        participants:
          type: "array"
          description: "Participants in the incident"
          items:
            $ref: "#/components/schemas/Participant"
        multimedias:
          type: "array"
          description: "Multimedia associated with the incident"
          items:
            $ref: "#/components/schemas/Multimedia"
        investigations:
          type: "array"
          description: "Investigations associated with the incident"
          items:
            $ref: "#/components/schemas/Investigation"
        results_of_stop:
          type: "array"
          description: "Results of stop associated with the incident"
          items:
            $ref: "#/components/schemas/ResultOfStop"
        actions:
          type: "array"
          description: "Actions associated with the incident"
          items:
            $ref: "#/components/schemas/Action"
        use_of_force:
          type: "array"
          description: "Use of force associated with the incident"
          items:
            $ref: "#/components/schemas/UseOfForce"
        legal_case:
          type: "array"
          description: "Legal case associated with the incident"
          items:
            $ref: "#/components/schemas/LegalCase"
    Incident:
      type: "object"
      description: "Incident object"
      properties:
        victims:
          type: "array"
          description: "Victims of the incident"
          items:
            $ref: "#/components/schemas/Victim"
        officers:
          type: "array"
          description: "Officers involved in the incident"
          items:
            $ref: "#/components/schemas/Officer"
        tags:
          type: "array"
          description: "Tags associated with the incident"
          items:
            type: "string"
        participants:
          type: "array"
          description: "Participants in the incident"
          items:
            $ref: "#/components/schemas/Participant"
        attachment:
          type: "array"
          description: "File attachments associated with the incident"
          items:
            $ref: "#/components/schemas/Attachment"
        investigations:
          type: "array"
          description: "Investigations associated with the incident"
          items:
            $ref: "#/components/schemas/Investigation"
        results_of_stop:
          type: "array"
          description: "Results of stop associated with the incident"
          items:
            $ref: "#/components/schemas/ResultOfStop"
        actions:
          type: "array"
          description: "Actions associated with the incident"
          items:
            $ref: "#/components/schemas/Action"
        use_of_force:
          type: "array"
          description: "Use of force associated with the incident"
          items:
            $ref: "#/components/schemas/UseOfForce"
        legal_case:
          type: "array"
          description: "Legal case associated with the incident"
          items:
            $ref: "#/components/schemas/LegalCase"
    IncidentList:
      type: "object"
      description: "Incident list response"
      properties:
        results:
          type: "array"
          description: "List of incidents"
          items:
            $ref: "#/components/schemas/Incident"
        page:
          type: "integer"
          description: "Page number of the results"
        totalPages:
          type: "integer"
          description: "Total number of pages"
        totalResults:
          type: "integer"
          description: "Total number of results"
