openapi: "3.0.3"
info:
  title: "Search"
  description: "API Description"
  version: "0.7.0"
servers:
  - url: "http://127.0.0.1:5001/api/v1"
    description: "Local environment"
  - url: "https://dev.nationalpolicedata.org/api/v1"
    description: "Staging environment"
  - url: "https://api.nationalpolicedata.org"
    description: "Production environment"
x-readme:
  explorer-enabled: true
  proxy-enabled: true
  samples-enabled: true
security:
  - bearerAuth: []
tags:
  - name: "Search"
    description: "Search API"
paths:
  /search:
    post: 
      tags: 
        - "Search"
      summary: "Search All"
      operationId: "searchAll"
      description: >
        Search the index for items that match the query. The search results can be filtered
        by content type, location, data source, and date range.
      parameters: 
        - $ref: '../common/pagination.yaml#/components/parameters/page'
        - $ref: '../common/pagination.yaml#/components/parameters/per_page'
      requestBody:
        description: >
          The search terms and the filters that should be applied to the search.
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SearchRequest"
      responses:
        "200":
          description: "Search results."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SearchResultList"
        '400':
          $ref: '../common/error.yaml#/components/responses/validationError'
        '404':
          $ref: '../common/error.yaml#/components/responses/notFoundError' 
  /search/auto:
    post:
      tags: 
        - "Search"
      summary: "Autocomplete Search Term"
      operationId: "autocomplete"
      description: >
        Returns a list of suggestions based on the search term.
      parameters: 
        - $ref: '../common/pagination.yaml#/components/parameters/page'
        - $ref: '../common/pagination.yaml#/components/parameters/per_page'
      requestBody:
        description: >
          The search term to get suggestions and any filters that should be applied to the search.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SearchRequest"
      responses:
        "200":
          description: "A list of suggested search terms."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SearchTerms"
        '400':
          $ref: '../common/error.yaml#/components/responses/validationError'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    SearchRequest:
      type: "object"
      properties:
        query:
          type: "string"
          description: "The search terms."
        filters:
          type: "object"
          properties:
            content_type:
              type: "string"
              description: "The type of content to search."
              enum:
                - "complaint"
                - "officer"
                - "agency"
                - "unit"
                - "litigation"
            location:
              $ref: "#/components/schemas/Location"
            data_source:
              type: "string"
              description: "The data source to search."
            date_earliest:
              type: "string"
              description: "Lower bound of the date range."
            date_latest:
              type: "string"
              description: "Upper bound of the date range."
    SearchResultList:
      allOf: 
        - $ref: '../common/pagination.yaml#/components/schemas/PaginatedResponse'
        - type: "object"
          properties:
            results:
              type: "array"
              items:
                $ref: "#/components/schemas/SearchResult"
    SearchResult:
      type: "object"
      properties:
        uid:
          type: "string"
          description: The unique identifier for the search result.
        title:
          type: "string"
          description: The title of the search result.
        subtitle:
          type: "string"
          description: The subtitle of the search result.
        details:
          type: "string"
          description: The details of the search result.
        content_type:
          type: "string"
          description: The type of content.
        source:
          $ref: "#/components/schemas/SourceRef"
        last_updated:
          type: "string"
          description: The date the content was last updated.
        href:
          type: "string"
          description: The URL of the search result.
    Location:
      type: "object"
      properties:
        name:
          type: "string"
          description: The name of the location.
        type:
          type: "string"
          description: The type of location.
          enum:
            - "city"
            - "county"
            - "state"
    SourceRef:
      type: "object"
      properties:
        name:
          type: "string"
          description: The name of the data source.
        href:
          type: "string"
          description: The URL of the data source.
    SearchTerms:
      type: "object"
      properties: 
        terms:
          type: "array"
          items:
            type: "string"