interface USState {
  initials: string
  name: string
}

export const states: USState[] = [
  { initials: "AK", name: "Alaska" },
  { initials: "AL", name: "Alabama" },
  { initials: "AR", name: "Arkansas" },
  { initials: "AS", name: "American Samoa" },
  { initials: "AZ", name: "Arizona" },
  { initials: "CA", name: "California" },
  { initials: "CO", name: "Colorado" },
  { initials: "CT", name: "Connecticut" },
  { initials: "DC", name: "District of Columbia" },
  { initials: "DE", name: "Delaware" },
  { initials: "FL", name: "Florida" },
  { initials: "GA", name: "Georgia" },
  { initials: "GU", name: "Guam" },
  { initials: "HI", name: "Hawaii" },
  { initials: "IA", name: "Iowa" },
  { initials: "ID", name: "Idaho" },
  { initials: "IL", name: "Illinois" },
  { initials: "IN", name: "Indiana" },
  { initials: "KS", name: "Kansas" },
  { initials: "KY", name: "Kentucky" },
  { initials: "LA", name: "Louisiana" },
  { initials: "MA", name: "Massachusetts" },
  { initials: "MD", name: "Maryland" },
  { initials: "ME", name: "Maine" },
  { initials: "MI", name: "Michigan" },
  { initials: "MN", name: "Minnesota" },
  { initials: "MO", name: "Missouri" },
  { initials: "MS", name: "Mississippi" },
  { initials: "MT", name: "Montana" },
  { initials: "NC", name: "North Carolina" },
  { initials: "NE", name: "Nebraska" },
  { initials: "NH", name: "New Hampshire" },
  { initials: "NJ", name: "New Jersey" },
  { initials: "NM", name: "New Mexico" },
  { initials: "NV", name: "Nevada" },
  { initials: "NY", name: "New York" },
  { initials: "ND", name: "North Dakota" },
  { initials: "OH", name: "Ohio" },
  { initials: "OK", name: "Oklahoma" },
  { initials: "OR", name: "Oregon" },
  { initials: "PA", name: "Pennsylvania" },
  { initials: "PR", name: "Puerto Rico" },
  { initials: "RI", name: "Rhode Island" },
  { initials: "SC", name: "South Carolina" },
  { initials: "SD", name: "South Dakota" },
  { initials: "TN", name: "Tennessee" },
  { initials: "TX", name: "Texas" },
  { initials: "UT", name: "Utah" },
  { initials: "VA", name: "Virginia" },
  { initials: "VT", name: "Vermont" },
  { initials: "WA", name: "Washington" },
  { initials: "WI", name: "Wisconsin" },
  { initials: "WV", name: "West Virginia" },
  { initials: "WY", name: "Wyoming" }
]
