name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get update
    - name: Deploy docs
      uses: mhausenblas/mkdocs-deploy-gh-pages@1.26
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CONFIG_FILE: docs/mkdocs.yml
        REQUIREMENTS: requirements/docs.txt
